# Generated by Django 4.2.29 on 2026-04-15 23:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLog',
            fields=[
                ('booklog', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pages_read', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklogs', to='Book.book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('update', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pages_today', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('review', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('booklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='User.booklog')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('pfp', models.ImageField(blank=True, default='fallback.png', null=True, upload_to='')),
                ('streak', models.IntegerField(default=0)),
                ('achievements', models.CharField(blank=True, max_length=100, null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booklog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklogs', to='User.profile'),
        ),
        migrations.CreateModel(
            name='ReadList',
            fields=[
                ('readlist', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readlist', to='User.profile')),
            ],
            options={
                'unique_together': {('book', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='User.profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='User.profile')),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='booklog',
            unique_together={('book', 'profile')},
        ),
    ]
