# Generated by Django 4.2.29 on 2026-04-08 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLog',
            fields=[
                ('booklog', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pages_read', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklogs', to='Book.book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('update', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pages_today', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('review', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('booklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='User.booklog')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('pfp', models.ImageField(blank=True, default='fallback.png', null=True, upload_to='')),
                ('streak', models.IntegerField(default=0)),
                ('achievements', models.CharField(blank=True, max_length=100, null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='User.user')),
            ],
        ),
        migrations.AddField(
            model_name='booklog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklogs', to='User.profile'),
        ),
        migrations.CreateModel(
            name='ReadList',
            fields=[
                ('readlist', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readlist', to='User.profile')),
            ],
            options={
                'unique_together': {('book', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='User.profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='User.profile')),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='booklog',
            unique_together={('book', 'profile')},
        ),
    ]
