# Generated by Django 4.2.29 on 2026-04-15 23:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, max_length=250, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, default='fallback.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('pages', models.IntegerField(default=0)),
                ('synopsys', models.TextField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=10, null=True)),
                ('cover', models.ImageField(blank=True, default='fallback.png', null=True, upload_to='')),
                ('year', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('editor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True, max_length=250, null=True)),
                ('founded', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Genre',
            fields=[
                ('book_genre', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Author',
            fields=[
                ('book_author', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='Book.Book_Author', to='Book.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Book.editor'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', through='Book.Book_Genre', to='Book.genre'),
        ),
    ]
